### ISSUE TITLE
500 err after 5mins

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cgadmin#6]
```130.229.43.125 - - [20/Apr/2017:11:15:22 +0200] "POST /admin/sample/edit/?id=39&url=%2Fadmin%2Fsample%2F%3Fpage%3D1 HTTP/1.1" 302 249 "https://clinical-db.scilifelab.se:8080/admin/sample/edit/?id=39&url=%2Fadmin%2Fsample%2F%3Fpage%3D1" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
2017-04-20 11:15:22 [45491] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 92, in handle
    req = six.next(parser)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/parser.py", line 40, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/message.py", line 151, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/message.py", line 51, in __init__
    unused = self.parse(self.unreader)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/message.py", line 163, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/message.py", line 154, in get_data
    data = unreader.read()
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/ssl.py", line 987, in recv
    return self.read(buflen)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/ssl.py", line 627, in read
    v = self._sslobj.read(len)
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:2178)
```
... and a bit further down the same error log ...

```
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/flask_admin/model/base.py", line 1818, in index_view
    view_args.search, view_args.filters)
  File "/home/hiseq.clinical/miniconda/envs/cgadmin/lib/python3.6/site-packages/pymysql/connections.py", line 1040, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))") [SQL: 'SELECT count(%(count_2)s) AS count_1 \nFROM sample'] [parameters: {'count_2': '*'}]
130.229.43.125 - - [20/Apr/2017:11:15:22 +0200] "GET /admin/sample/?page=1 HTTP/1.1" 500 291 "https://clinical-db.scilifelab.se:8080/admin/sample/edit/?id=39&url=%2Fadmin%2Fsample%2F%3Fpage%3D1" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
```
The site is not usable anymore ater this and all page requests return a `500`.
Restarting the process makes the site usable again.

**Comment by robinandeer** [comment]
Yeah I've seen this error - really annoying but the solution now is to revert to using the deprecated "Flask-Alchy" package... that's why I've been holding off but I don't understand how to fix the problem myself

**Comment by robinandeer** [comment]
I can try to reach out to the author of SQLService one last time
